# Generated by Django 4.1.7 on 2023-02-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_category_wishlist_hirebook_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirebook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='hirebook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='hirebook',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hirebook',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hirebook',
            name='hire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
