# Generated by Django 4.1.7 on 2023-03-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_hirebook_book_remove_hirebook_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
