# Generated by Django 4.1.7 on 2023-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_user_address_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirebook',
            name='book_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
