# Generated by Django 4.1.7 on 2023-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_hirebook_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirebook',
            name='book_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
