# Generated by Django 4.1.7 on 2023-03-07 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_hirebook_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='buy_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=200),
        ),
    ]
