# Generated by Django 4.1.7 on 2023-03-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_created_at_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='files/default.pdf', upload_to='files'),
        ),
    ]
